# DRAFT_CLASS_NAME = "wbf-2121-draft"
DRAFT_CLASS_NAME = "yfmlb-2042-draft"
# DRAFT_CLASS_NAME = "yfmlb-2042-prospects"
STATS_PLUS_URL = "https://statsplus.net/yfmlb/"
# STATS_PLUS_URL = "https://atl-01.statsplus.net/wbf/"
